language: objective-c
cache: cocoapods
before_install:
- pod repo --silent update

xcode_workspace: Swindler.xcworkspace
xcode_scheme: Swindler

osx_image: xcode8.3
xcode_sdk: macosx10.12
script: xcodebuild -workspace Swindler.xcworkspace -scheme Swindler -sdk macosx10.12 build test
